" ===========================================================
" | PERSONAL VIM CONFIG | https://github.com/K750i/dotfiles |
" ===========================================================

" -------------------------------------------------
" VIM-PLUG CONFIGURATIONS
" reload .vimrc and :PlugInstall to install plugins
" -------------------------------------------------
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'drewtempelmeyer/palenight.vim'
Plug 'itchyny/lightline.vim'
Plug 'machakann/vim-highlightedyank'
Plug 'mattn/emmet-vim', { 'for': ['html', 'css'] }

call plug#end()

" ----------------------
" GENERAL CONFIGURATIONS
" ----------------------
filetype plugin indent on                       " Enable file type detection, loading of indent & plugin files
runtime macros/matchit.vim                      " Extended matching with '%'
syntax on					" turn on syntax highlighting
set autoindent                                  " Copy indent to new line
set backspace=indent,eol,start                  " Allow backspace in Insert Mode
set cursorline					" highlight current line
set encoding=utf8                               " Set utf8 as standard encoding and en_US as standard language
set hidden                                      " Possibility to have more than one unsaved buffers
set history=500                                 " Store a ton more history than default
set ignorecase                                  " Case insensitive search
set inccommand=nosplit                          " highlight text while using the substitution command
set incsearch                                   " Incremental and highlight search during typing
set lazyredraw                                  " Don't redraw while executing macros
set magic                                       " For regular expressions
set mouse=a                                     " Enable mouse usage (all modes)
set noerrorbells                                " Disable error bells
set nojoinspaces                                " Prevents inserting two spaces after punctuation on a join (J)
set novisualbell                                " Disable visual error indicator
set hlsearch                                    " turn on search highlighting
set noshowmode                                  " don't show vim's default status message
set nowrap					" don't wrap long lines
set number                                      " Enable line numbering
set relativenumber				" show line number relative to cursor
set scrolloff=3                                 " Keep the cursor 3 lines above & below the screen when scrolling
set smartcase                                   " Override 'ignorecase' if search contains uppercase characters.
set softtabstop=2 shiftwidth=2 expandtab	" 2 tab sizes and always use spaces instead of tabs
set splitbelow                                  " Put new split window on the bottom of current window
set splitright                                  " Put new split window on the right of current window
set wildmenu                                    " Visual autocomplete for command menu

if (has("termguicolors"))                       " Enable true colors
  set termguicolors
endif

" --------------------------
" SET LIGHTLINE COLOR SCHEME
" --------------------------
let g:lightline = {'colorscheme': 'wombat'}

" -----------------------
" MATERIAL THEME SETTINGS
" -----------------------
let g:material_theme_sytle = 'palenight'
let g:material_terminal_italics = 1

" -----------------------
" SET BUFFER COLOR SCHEME
" -----------------------
colorscheme palenight
set background=dark

" ------------------
" CUSTOM KEY MAPPING
" ------------------
let mapleader=","
nmap <leader>vi :tabedit ~/Documents/code/dotfiles/vim/vimrc<cr>
nmap <leader>so :source ~/Documents/code/dotfiles/vim/vimrc<cr>
nmap <leader>rp :w<cr>:!python3 %<cr>
nmap <leader>sv :w<cr>

nnoremap <silent> <c-l> :<c-u>nohlsearch<cr><c-l>
imap wf <esc>

" ---------
" AUTOGROUP
" ---------
augroup configgroup
  autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
augroup end
